[package]
name = "rsync-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8", package = "libadwaita", features = ["v1_8"] }
gtk = { version = "0.10", package = "gtk4", features = ["v4_20"] }

[build-dependencies]
glib-build-tools = "0.21"
